
package dz.acs.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HolidayFrontApi", targetNamespace = "http://ws.acs.dz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HolidayFrontApi {


    /**
     * 
     * @param arg0
     * @return
     *     returns dz.acs.ws.client.HolidayResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ask", targetNamespace = "http://ws.acs.dz/", className = "dz.acs.ws.client.Ask")
    @ResponseWrapper(localName = "askResponse", targetNamespace = "http://ws.acs.dz/", className = "dz.acs.ws.client.AskResponse")
    @Action(input = "http://ws.acs.dz/HolidayFrontApi/askRequest", output = "http://ws.acs.dz/HolidayFrontApi/askResponse")
    public HolidayResponse ask(
        @WebParam(name = "arg0", targetNamespace = "")
        HolidayRequest arg0);

}
